---
# vars file for timetracking-bot
timetracking_bot_config:
  homeserver_url: "{{ timetracking_bot_homeserver_url }}"
  mxid: "{{ timetracking_bot_mxid }}"
  password: "{{ timetracking_bot_password }}"
  store_path: "{{ timetracking_bot_store_path }}"
  session_path: "{{ timetracking_bot_session_path }}"
  database_url: "{{ timetracking_bot_pg_url }}"
  admins: "{{ timetracking_bot_admins }}"
  allowed_users: "{{ timetracking_bot_allowed_users }}"

timetracking_bot_docker_labels_complete: "{{ timetracking_bot_docker_labels_base | combine(timetracking_bot_docker_labels) }}"
timetracking_bot_docker_labels_base:
  version: "{{ timetracking_bot_container_image_tag | default(timetracking_bot_version, true) }}"
