---
matrix_hs_url: ~
matrix_token: ~

matrix_room_alias: ~
matrix_room_name: ~
matrix_room_topic: ~
matrix_room_enable_encryption: false
matrix_room_join_rule: ~
matrix_room_join_rules_restricted_allow: []
# Array of dicts. Each event one dict, containing type, key and content
matrix_room_additional_state: []
