---
# tasks file for panopticon
- name: Launch mariadb for panopticon
  become: true
  community.docker.docker_container:
    name: panopticon-db
    image: "docker.io/mariadb:{{ panopticon_db_version }}"
    volumes:
      - /opt/panopticon/database:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{ panopticon_db_password }}"
      MYSQL_DATABASE: "{{ panopticon_db_name }}"
      MYSQL_USER: "{{ panopticon_db_user }}"
      MYSQL_PASSWORD: "{{ panopticon_db_password }}"
    restart_policy: unless-stopped
    labels: "{{ panopticon_db_docker_labels_complete }}"
    ports: "{{ panopticon_db_docker_ports }}"

- name: Launch panopticon
  become: true
  community.docker.docker_container:
    name: panopticon
    image: registry.gitlab.com/famedly/containers/panopticon
    pull: true
    links:
      - panopticon-db:mariadb
    labels: "{{ panopticon_docker_labels_complete }}"
    ports: "{{ panopticon_docker_ports }}"
    env:
      PANOPTICON_DB_DRIVER: mysql
      PANOPTICON_DB: "{{ panopticon_db_dsn }}"
      PANOPTICON_PORT: "8000"
    restart_policy: unless-stopped
